name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install UV
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Create virtual environment
      run: |
        uv venv

    - name: Install dependencies (including deepeval + langchain_azure_ai)
      run: |
        source .venv/bin/activate
        uv pip install -e ".[dev]"
        uv pip install deepeval langchain-azure-ai


    - name: Run Ruff
      run: |
        source .venv/bin/activate
        ruff check .
        ruff format --check .

    - name: Run mypy
      run: |
        source .venv/bin/activate
        mypy .

    - name: Run tests with coverage
      run: |
        source .venv/bin/activate
        pytest --cov=ask_rag --cov-report=term
