name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install UV
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Create virtual environment and install dependencies
      run: |
        uv venv
        .venv/bin/uv pip install -e ".[dev]"
        .venv/bin/uv pip install deepeval langchain-azure-ai

    - name: Format code
      run: .venv/bin/ruff format .

    - name: Lint code
      run: .venv/bin/ruff check .

    - name: Static type check
      run: .venv/bin/mypy .

    - name: Run tests
      run: .venv/bin/pytest --cov=ask_rag --cov-report=term
