name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install UV
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Create virtual environment
      run: |
        uv venv
        source .venv/bin/activate

    - name: Install dependencies
      run: |
        source .venv/bin/activate
        uv pip install -e ".[dev]"

    - name: Run Ruff
      run: |
        source .venv/bin/activate
        ruff check .
        ruff format --check .

    - name: Run mypy
      run: |
        source .venv/bin/activate
        mypy .

    - name: Run tests with coverage
      run: |
        source .venv/bin/activate
        pytest --cov=src --cov-report=term --cov-fail-under=70

