name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Create and activate virtual environment
      run: |
        python -m venv .venv
        . .venv/bin/activate
        python -m pip install --upgrade pip setuptools wheel

    - name: Install dependencies (including deepeval + langchain_azure_ai)
      run: |
        . .venv/bin/activate
        pip install -e ".[dev]"
        pip install deepeval langchain-azure-ai pytest pytest-cov ruff mypy

    - name: Run Ruff format
      run: |
        . .venv/bin/activate
        ruff format .

    - name: Run Ruff check
      run: |
        . .venv/bin/activate
        ruff check .

    - name: Run mypy
      run: |
        . .venv/bin/activate
        mypy .

    - name: Run tests with coverage
      run: |
        . .venv/bin/activate
        pytest --cov=ask_rag --cov-report=term

    - name: Debug on failure
      if: failure()
      run: |
        echo "Debug info:"
        ls -la
        which python || echo "python not found"
        env | grep -i "python\|venv"
